PM-Dungeon/dungeon-starter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
Die Templates für die Issues/PRs sind nun zweisprachig. 
Würde ich auch so im `core` hinzufügen.
=> Templates sind nun zweisprachig

code/build.gradle
Siehe Issue 133 im anderen Repo
=> Fix dependencies, build.gradle updated

code/build.gradle
Nur Kleinigkeiten wie "nutze immer die neuste Version von core" usw.
=> Maven: Update build.gradle

code/desktop/src/desktop/DesktopLauncher.java
=> DesktopLauncher: Remove main method

.github/workflows/github_ci.yml, .gitlab-ci.yml
Fixes #29 
fixes #30 
Bitte hier noch schnell genehmigen, dann kann ich gl und muster nachziehen... :)
=> Workflow: Transfer

code/desktop/src/com/badlogic/gdx/backends/lwjgl/DungeonApplication.java, code/desktop/src/desktop/DesktopLauncher.java
Wie besprochen habe ich das jetzt mal implementiert. Mir ist nur aufgefallen das es noch keine wirkliche Beschreibung gibt welche Sprache Docs sein sollen bzw. wie stark und genau sie sein sollen.
solves #24
=> Statuscode -1 behoben, Default Close Operation

documentation/quickstart_de.md
Code now correctly reflects the specifications mentioned in class diagram.
=> Fixed typo in quickstart_de.md

code/build.gradle, code/desktop/src/desktop/MyGame.java
Fixed #56 
- Minimales `MyGame`
- `main` Methode
- Klasse als Startpunkt in `build.gradle` angelegt.
=> add MyGame zur Vorgabe 

documentation/quickstart_de.md
Fixes #44 #43 #40 
Ich habe die Dokumentation nochmal generalüberholt.
Bitte einmal Probelesen.
Ich habe dabei schon #58 beachtet und hab mich an die aktuelle `core` Version gehalten, der Release ist etwas outdated. 
@jedi101 wenn du Zeit hast, kannst du gerne mal Grammatik-Check machen. Ich neige dazu, entweder Inhalt zu erschaffen oder Grammatik einzuhalten, beides kann ich nicht.
=> rework quickstart

code/build.gradle
Neue Version des core. 
muss noch auf mavencentral warten ☕
=> use core 3.0.+

documentation/quickstart_en.md
Fixes #41.
Still, a work in progress because my English is not the yellow from the egg.
**updated:**
=> translated quickstart_de -> quickstart_en

documentation/quickstart_de.md
=> Whitespace: fix errors

code/build.gradle
Update: build.gradle, avoid deprecated features
Fixes #79
=> Update: build.gradle, avoid deprecated features

code/build.gradle
Update: build.gradle and rename desktop
=> Update: build.gradle

code/build.gradle, code/desktop/src/com/badlogic/gdx/backends/lwjgl/DungeonApplication.java, code/desktop/src/desktop/DesktopLauncher.java, code/desktop/src/desktop/MyGame.java, code/gradle.properties
Siehe auch: https://github.com/PM-Dungeon/core/issues/66
Das ist nur zum Ausprobieren und wird nicht gemerged...
@cagix bitte damit einmal testen...
=> Fix: Mac, Update: build.gradle, lwjgl3 instead of lwjgl

documentation/quickstart_de.md
=> Fix #94 added link to compatibility list of jdk versions

code/checkstyle-config/checks.xml, code/desktop/src/desktop/DesktopLauncher.java, code/desktop/src/desktop/MyGame.java, code/desktop/test/desktop/DesktopLauncherTest.java
Fixes https://github.com/PM-Dungeon/core/issues/156
=> Update check style file

.github/workflows/github_ci.yml
Fixes https://github.com/PM-Dungeon/core/issues/274
=> Update github_ci.yml checkstyle

.github/workflows/github_ci.yml
siehe auch https://github.com/PM-Dungeon/core/issues/277 und https://github.com/PM-Dungeon/dungeon-starter/pull/106
=> Update workflow github_ci.yml

code/build.gradle
Wir hatten in `core/version4` das Buildscript angepasst, diese Änderungen sind jetzt auch hier.
siehe https://github.com/PM-Dungeon/core/pull/291 fixes https://github.com/PM-Dungeon/core/issues/290
=> Update buildscript to that one in core/version4

README.md
Notiz zum archivieren des Repos.
Issues und PRs sind mit `wontfix` geclosed. 
Danach mach ich dicht.
=> close repo
